### ISSUE TITLE
no_std support

### ISSUE THREAD

**Issue by tarcieri** [cesarb/clear_on_drop#11]
I'd like to use this crate in `#![no_std]` environments. It looks like it wouldn't be hard to support.

I can send a PR if you'd like.

**Comment by cesarb** [comment]
If you want to, go ahead. From a quick look, it won't be totally trivial, since core seems to be missing for instance `ptr::write_bytes` (aka memset), but it shouldn't be hard to do.

**Comment by tarcieri** [comment]
That's also available in `core::ptr`:

https://doc.rust-lang.org/core/ptr/
